
### TEST ROUTE SIGNUP
POST http://localhost:5050/signup HTTP/1.1
Content-Type: application/json

{
    "username": "aaa",
    "email": "aaa@aaa.aaa",
    "password": "aaa"
}

### TEST ROUTE LOGIN
POST http://localhost:5050/login HTTP/1.1
Content-Type: application/json

{
    "email": "aaa@aaa.aaa",
    "password": "aaa"
}

### TEST ROUTE TOOLS
GET http://localhost:5050/tools HTTP/1.1
